---
build_from:
  aarch64: ghcr.io/hassio-addons/base:20.0.1
  amd64: ghcr.io/hassio-addons/base:20.0.1
args:
  BABYBUDDY_GIT_URL: https://github.com/kreucher/babybuddy.git
  BABYBUDDY_GIT_REF: kreucher-v2.10.0-ux.6
